#!/bin/bash 

#vars
array=($(ls *.pdf)) #array with 10 elem
array_len=${#array[@]} #get len of array
iterate=0 #index

for i in "${array[@]}"; do #iterate
    let iterate=${iterate}+1 #refresh iteration
    if [[ $iterate -eq $array_len ]]; then #verify
        echo -n -e "This is the last iterate\nThe last item of array is $i"
    else
        echo "This not is the last iterate"
    fi
done
